version: "3.7"
services:
  health-check:
    depends_on:
      localstack:
        condition: service_healthy
    image: alpine:latest
    command: echo "Health check done."

  # Services to facilitate S3 bucket are localstack, s3Bucket
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports:
      - "4566-4583:4566-4583"
    volumes:
      - "./docker/localstacks3:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: awslocal s3 mb s3://testbucket
    healthcheck:
      test: [ "CMD", "bash", "-c", "awslocal s3 ls" ]
      interval: 5s
      timeout: 10s
      retries: 15
  s3Bucket:
    image: amazon/aws-cli
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    command: --no-sign-request --endpoint-url=http://localstack:4566 s3 mb s3://media-store
    depends_on:
      localstack:
        condition: service_healthy
  streamSQSQueue:
    image: amazon/aws-cli
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    command: --no-sign-request --endpoint-url=http://localstack:4566 sqs create-queue --queue-name stream-shows.fifo --attributes FifoQueue=true,VisibilityTimeout=60,ContentBasedDeduplication=true
    depends_on:
      localstack:
        condition: service_healthy
  scriptSQSQueue:
    image: amazon/aws-cli
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    command: --no-sign-request --endpoint-url=http://localstack:4566 sqs create-queue --queue-name script-shows.fifo --attributes FifoQueue=true,VisibilityTimeout=60,ContentBasedDeduplication=true
    depends_on:
      localstack:
        condition: service_healthy

  icecast:
    image: vimagick/icecast
    ports:
      - "8000:8000"
    restart: always
