
[project]
name = "wet-toast-talk-radio"
version = "0.1.0"
description = ""
authors = [
    { name = "camille-vanhoffelen", email = "camille-vanhoffelen@users.noreply.github.com" },
    { name = "raphael-vanhoffelen", email = "dskart11@gmail.com" },
]
dependencies = [
    "suno-bark @ git+https://github.com/suno-ai/bark.git",
    "nltk>=3.8.1",
    "structlog>=23.1.0",
    "click>=8.1.3",
    "pydantic>=1.10.8",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
[project.optional-dependencies]
ide = ["setuptools>=67.8.0"]


[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.3.0",
    "pylint>=2.17.4",
]

[tool.setuptools]
py-modules = []
