line-length = 120
respect-gitignore = true
target-version = "py310"

[lint]
select = ["E", "W", "F", "B", "Q", "I", "ASYNC", "FBT", "A", "PIE", "PYI", "PT", "SLF", "SIM", "ARG", "PTH", "ERA", "PL", "PLR", "PLW", "PLC", "PLE", "RUF"]
ignore = ["PT009"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.extend-per-file-ignores]
"*/tests/*" = ["SLF001"]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.flake8-pytest-style]
# Disable the following rules:
