let md = window.markdownit({ html: true });
const windowContentContainer = document.getElementById("window-content");
const contentMap = new Map();

// https://markdown-it.github.io/

const infoContent = `

<p><b>A 24/7 non-stop internet parody radio inspired by GTA and generated by AI.</b></p>

<p>
<a href="https://www.twitch.tv/wettoasttalkradio" target="_blank">
  <i class="nes-icon twitch"></i>
</a>
We stream non-stop on <a href="https://www.twitch.tv/wettoasttalkradio" target="_blank">Twitch</a>!</p>

<p>
<a href="https://ko-fi.com/wettoasttalkradio" target="_blank">
  <img alt="Ko-fi logo" src="kofi-logo.png" width="40px"/>
</a>
Support us on <a href="https://ko-fi.com/wettoasttalkradio" target="_blank">Ko-fi</a>!</p>

<p>Made with <3 by:</p>

- Camille Van Hoffelen
<a href="https://github.com/camille-vanhoffelen" target="_blank">
  <i class="nes-icon github"></i>
</a>
<a href="https://linkedin.com/in/camillevanhoffelen" target="_blank">
  <i class="nes-icon linkedin"></i>
</a>
- Raphael Van Hoffelen
<a href="https://github.com/dskart" target="_blank">
  <i class="nes-icon github"></i>
</a>
<a href="https://www.linkedin.com/in/raphael-van-hoffelen-ba6393137" target="_blank">
  <i class="nes-icon linkedin"></i>
</a>
`;
contentMap.set("info-tab", infoContent);

const creditsContent = `
Thank you for your support:
- Berenike Melchior
- All the smart, beautiful people who gave feedback

Built with:
- Text-to-Speech from <a href="https://github.com/neonbjb/tortoise-tts" target="_blank">tortoise-tts</a>
- 'Modern Mindfulness' background music from <a href="https://pixabay.com/music/meditationspiritual-relaxing-music-vol1-124477/" target="_blank">RelaxingTime</a>
- GTA V video gameplay by <a href="https://www.youtube.com/@DopeGameplays" target="_blank">DopeGameplays</a>
- Voice samples for conditioning latents from <a href="https://datashare.ed.ac.uk/handle/10283/3443" target="_blank">CSTR VCTK Corpus</a>
- Splash sound sample from <a href="https://pixabay.com/sound-effects/dive-6423/" target="_blank">Pixabay</a>
- CSS framework from <a href="https://nostalgic-css.github.io/NES.css" target="_blank">NES.css</a>
- Inspiration from Rockstar Games' brilliant radios
`;
contentMap.set("credits-tab", creditsContent);

const faqContent = `
<h3>Why did you make WTTR?</h3>

<p>For the giggles.</p>

<h3>How does WTTR work?</h3>

<p>First, the radio show scripts are written with ChatGPT. Much prompt-engineering and randomization goes into this step.
Then these are fed into our speech generation cluster which runs <a href="https://github.com/neonbjb/tortoise-tts" target="_blank">tortoise-tts</a>. We generate audio slower than real-time, so we need more than one machine to keep up!
Finally, we transcode all the audio files, and stream them to our Icecast server.
We schedule the whole pipeline in batches so we can ensure that there is always 24 hours of content ready at the start of each day.</p>

<h3>Are the characters based on real people?</h3>

<p>No. They were invented and prompt-engineered to be comical. The voices however are based on real people from an <a href="https://datashare.ed.ac.uk/handle/10283/3443" target="_blank">open source dataset</a>.</p>

<h3>Why are there voice glitches?</h3>

<p>In order to be funny, voices have to be expressive. And generating expressive speech is hard. Most of the state-of-the-art models are not freely available, at costs too high for 24/7 generation.
Instead, the best open source model we experimented with (tortoise-tts) was generously trained by a <a href="https://arxiv.org/abs/2305.07243" target="_blank">single person on their own hardware for a year</a>.
Also our inference server costs are still high, so we have to use faster and lower quality presets.
This is why it sounds like we have ghosts on the show from time to time.</p>

<h3>Why do characters sometimes get stuck in a conversation loop?</h3>
<p>Because prompt-engineering is hard. Also because ChatGPT loves being <a href="https://huggingface.co/blog/rlhf" target="_blank">helpful and thankful</a>.</p>

<h3>Why is there a music loop playing?</h3>
<p>Something is probably broken... we are working on fixing it!</p>
`;
contentMap.set("faq-tab", faqContent);

function setWindowContent(contentId) {
  windowContentContainer.innerHTML = md.render(contentMap.get(contentId));
}

function showContentMenu(containerId) {
  setWindowContent(containerId);
}

showContentMenu("info-tab");

/* Open with warning */
document.getElementById('dialog-dark-rounded').showModal();
