name: Build
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: 289115055556.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_NAME: wet-toast-talk-radio

jobs:
  build:
    name: ECR Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Build
      run: |
        docker build -t wettoast .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::289115055556:role/GitHubActionsWetToastTalkRadio
        aws-region: us-east-1
    - name: Docker Push
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 289115055556.dkr.ecr.us-east-1.amazonaws.com
        docker tag wettoast:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{  github.ref_name }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{  github.ref_name }}