name: Python

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          pdm sync -d
          
      - name: Lint
        run: |
          pdm run black ./ --check --verbose
          pdm run ruff check .
          
#       - name: Run Tests
#         run: |
#          pdm run -v pytest tests
