name: Python

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_REGION: us-east-1

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libavcodec-extra libgomp1 
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Test with pytest
        run: |
          pytest -v

  linting:
    name: Linting/Formatting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libavcodec-extra libgomp1 
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Lint with ruff
        run: |
          black ./ --check 
          ruff check .